//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_BD.ServiceWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCAlumno", Namespace="http://schemas.datacontract.org/2004/07/WCF_Primero")]
    [System.SerializableAttribute()]
    public partial class DCAlumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string curpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEstadoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> idEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                if ((object.ReferenceEquals(this.curpField, value) != true)) {
                    this.curpField = value;
                    this.RaisePropertyChanged("curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEstadoOrigen {
            get {
                return this.idEstadoOrigenField;
            }
            set {
                if ((this.idEstadoOrigenField.Equals(value) != true)) {
                    this.idEstadoOrigenField = value;
                    this.RaisePropertyChanged("idEstadoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> idEstatus {
            get {
                return this.idEstatusField;
            }
            set {
                if ((this.idEstatusField.Equals(value) != true)) {
                    this.idEstatusField = value;
                    this.RaisePropertyChanged("idEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IWCFAlumno")]
    public interface IWCFAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Consultar", ReplyAction="http://tempuri.org/IWCFAlumno/ConsultarResponse")]
        Datos_BD.ServiceWCF.DCAlumno[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Consultar", ReplyAction="http://tempuri.org/IWCFAlumno/ConsultarResponse")]
        System.Threading.Tasks.Task<Datos_BD.ServiceWCF.DCAlumno[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Create", ReplyAction="http://tempuri.org/IWCFAlumno/CreateResponse")]
        void Create(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Create", ReplyAction="http://tempuri.org/IWCFAlumno/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Actualizar", ReplyAction="http://tempuri.org/IWCFAlumno/ActualizarResponse")]
        void Actualizar(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Actualizar", ReplyAction="http://tempuri.org/IWCFAlumno/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/detail", ReplyAction="http://tempuri.org/IWCFAlumno/detailResponse")]
        Datos_BD.ServiceWCF.DCAlumno detail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/detail", ReplyAction="http://tempuri.org/IWCFAlumno/detailResponse")]
        System.Threading.Tasks.Task<Datos_BD.ServiceWCF.DCAlumno> detailAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Edit2", ReplyAction="http://tempuri.org/IWCFAlumno/Edit2Response")]
        void Edit2(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Edit2", ReplyAction="http://tempuri.org/IWCFAlumno/Edit2Response")]
        System.Threading.Tasks.Task Edit2Async(Datos_BD.ServiceWCF.DCAlumno alumnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Eliminar", ReplyAction="http://tempuri.org/IWCFAlumno/EliminarResponse")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/Eliminar", ReplyAction="http://tempuri.org/IWCFAlumno/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAlumnoChannel : Datos_BD.ServiceWCF.IWCFAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAlumnoClient : System.ServiceModel.ClientBase<Datos_BD.ServiceWCF.IWCFAlumno>, Datos_BD.ServiceWCF.IWCFAlumno {
        
        public WCFAlumnoClient() {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Datos_BD.ServiceWCF.DCAlumno[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<Datos_BD.ServiceWCF.DCAlumno[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public void Create(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            base.Channel.Create(alumnos);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            return base.Channel.CreateAsync(alumnos);
        }
        
        public void Actualizar(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            base.Channel.Actualizar(alumnos);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            return base.Channel.ActualizarAsync(alumnos);
        }
        
        public Datos_BD.ServiceWCF.DCAlumno detail(int id) {
            return base.Channel.detail(id);
        }
        
        public System.Threading.Tasks.Task<Datos_BD.ServiceWCF.DCAlumno> detailAsync(int id) {
            return base.Channel.detailAsync(id);
        }
        
        public void Edit2(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            base.Channel.Edit2(alumnos);
        }
        
        public System.Threading.Tasks.Task Edit2Async(Datos_BD.ServiceWCF.DCAlumno alumnos) {
            return base.Channel.Edit2Async(alumnos);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
